### ISSUE TITLE
some question about etcd lock API behavior

### ISSUE THREAD

**Issue by HuanGong** [etcd-cpp-apiv3/etcd-cpp-apiv3#30]
according to he api implement in golang，seems need create a lease and keepalive it to make sure lock success or fail.  what the behavior need be when program crash after a success locking.  base on current code, it seems will cause whole distribution session by locked forever? 

any reference can define those behavior?  thanks for your great job for c++ implement again.

**Comment by sighingnow** [comment]
Previously "lock" is implemented using a "default lease", which will be created by etcd server implicitly and the TTL is usually 60 seconds (by default). Obviously, that is _buggy_.

Thanks for bring such a bug to us and will be fixed by #31, After that pull request been merged, a "lock" can accept a user-provided lease, or create a lease and "keep alive" it implicitly.

**Comment by HuanGong** [comment]
thanks.
